apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: read-deployments-binding
  namespace: rbac-ns
subjects:
- kind: User
  name: ijeawele
  apiGroup: rbac.authorization.k8s.io
roleRef: 
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
